### PR TITLE
Fix 'TypeError: Invalid URL'

### PR DESCRIPTION
**Pull request by goodwise**
Fix an issue of `import.meta.url` being undefined, in which case Node.JS throws an exception `TypeError: Invalid URL`.

Got this error when attempted to run compiled by esbuild code of my CommonJS project - probably `import.meta.url` is set to undefined in CJS and to the correct value for ESM.

### CODE REVIEW

**Comment by hildjj** [comment]
Hm, I was afraid we were going to run into an issue like this.  I think I'd like to fix this a different way, using https://github.com/hildjj/package-extract to pull the bits we need out of package.json at compile time.  I think that approach should work in all situations.

I'm going to leave this open, whip up a parallel PR, and ask for your review.

**Comment by goodwise** [comment]
Just found a much better way to solve this issue, seems to be simple and elegant:

```javascript
import {name as pkgName, version as pkgVersion} from '../package.json';
```

**Comment by hildjj** [comment]
Sorry, I just realized my tests aren't running correctly on pull requests, or you would have seen errors when you pushed this change.

Imports from JSON files don't work in node.js unless both of these things are true:
- node.js v20.10 or later
- you add `with { type: "json" }` at the end of the import

I'm still going to support node.js v18 until it goes end-of-support in April 2025.

Given that, I think #59 is a better solution, unless you have an issue with that approach.

**Comment by goodwise** [comment]
@hildjj, If you don't like the above idea of using the `require` statement, then just pull #59

**Comment by hildjj** [comment]
Closed in favor of #59

**Pull request closed without merging**
